# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: Go-Web-Application-DevOps 
  labels:
    app: Go-Web-Application-DevOps 
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: Go-Web-Application-DevOps 
  type: ClusterIP